spring.application.name=house_paint

# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/paint_pos
spring.datasource.username=root
spring.datasource.password=ThzDeveloper#162026

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional: format SQL logs
spring.jpa.properties.hibernate.format_sql=true
